import React from 'react';

interface WordCloudAnimationProps {
  words: string[][];
}

const WordCloudAnimation: React.FC<WordCloudAnimationProps> = ({ words }) => {
  return (
    <div className="static [align-items:normal] box-content gap-x-[normal] block flex-row shrink h-auto justify-normal gap-y-[normal] transform-none w-auto z-auto left-auto top-auto md:absolute md:content-center md:items-center md:aspect-auto md:box-border md:gap-x-2.5 md:flex md:flex-col md:shrink-0 md:h-min md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-50.0%] md:translate-y-[-50.0%] md:w-[132%] md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-2/4 md:top-2/4">
      {words.map((wordList, index) => (
        <div key={index} className="static box-content shrink h-auto min-h-0 min-w-0 w-auto z-auto md:relative md:aspect-auto md:box-border md:shrink-0 md:h-[60px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <section className="[align-items:normal] box-content block h-auto list-disc max-h-none max-w-none w-auto md:[mask-image:linear-gradient(to_right,rgba(0,0,0,0)_0%,rgb(0,0,0)_12.5%,rgb(0,0,0)_87.5%,rgba(0,0,0,0)_100%)] md:items-center md:aspect-auto md:box-border md:flex md:h-full md:justify-items-center md:list-none md:max-h-full md:max-w-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:p-2.5 md:scroll-m-0 md:scroll-p-[auto]">
            <ul className={index === 1 ? "static [align-items:normal] box-content gap-x-[normal] block h-auto max-h-none max-w-none min-h-0 min-w-0 gap-y-[normal] transform-none w-auto pl-10 left-auto md:relative md:items-center md:aspect-auto md:box-border md:gap-x-5 md:flex md:h-full md:justify-items-center md:left-[-720px] md:max-h-full md:max-w-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[99.9957px] md:w-full md:[mask-position:0%] md:bg-left-top md:pl-0 md:scroll-m-0 md:scroll-p-[auto]" : index === 2 ? "static [align-items:normal] box-content gap-x-[normal] block h-auto max-h-none max-w-none min-h-0 min-w-0 gap-y-[normal] transform-none w-auto pl-10 left-auto md:relative md:items-center md:aspect-auto md:box-border md:gap-x-5 md:flex md:h-full md:justify-items-center md:left-[-632px] md:max-h-full md:max-w-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[99.9957px] md:w-full md:[mask-position:0%] md:bg-left-top md:pl-0 md:scroll-m-0 md:scroll-p-[auto]" : index === 3 ? "static [align-items:normal] box-content gap-x-[normal] block h-auto max-h-none max-w-none min-h-0 min-w-0 gap-y-[normal] transform-none w-auto pl-10 left-auto md:relative md:items-center md:aspect-auto md:box-border md:gap-x-5 md:flex md:h-full md:justify-items-center md:left-[-642px] md:max-h-full md:max-w-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[99.9957px] md:w-full md:[mask-position:0%] md:bg-left-top md:pl-0 md:scroll-m-0 md:scroll-p-[auto]" : "static [align-items:normal] box-content gap-x-[normal] block h-auto max-h-none max-w-none min-h-0 min-w-0 gap-y-[normal] transform-none w-auto pl-10 md:relative md:items-center md:aspect-auto md:box-border md:gap-x-5 md:flex md:h-full md:justify-items-center md:max-h-full md:max-w-full md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-x-[-99.9957px] md:w-full md:[mask-position:0%] md:bg-left-top md:pl-0 md:scroll-m-0 md:scroll-p-[auto]"}>
              {wordList.map((word, wordIndex) => (
                <li key={wordIndex} className="box-content min-h-0 min-w-0 text-left md:aspect-auto md:box-border md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                  <div className="static [align-items:normal] box-content gap-x-[normal] block shrink h-auto justify-normal gap-y-[normal] w-auto md:relative md:content-center md:items-center md:aspect-auto md:box-border md:gap-x-2.5 md:flex md:shrink-0 md:h-[53px] md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2.5 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-min md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                    <div className="static box-content block flex-row shrink justify-normal min-h-0 min-w-0 opacity-100 text-wrap md:relative md:aspect-auto md:box-border md:flex md:flex-col md:shrink-0 md:justify-center md:min-h-[auto] md:min-w-[auto] md:opacity-30 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                      <h3 className="text-black text-[18.72px] box-content leading-[normal] min-h-0 min-w-0 text-start text-wrap font-times md:text-white md:text-[40px] md:aspect-auto md:box-border md:leading-[48px] md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-inter_display">{word}</h3>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </section>
        </div>
      ))}
    </div>
  );
};

export default WordCloudAnimation;
